/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.Font;
import javax.swing.table.JTableHeader;

/**
 *
 * @author PC
 */
public class QLKhoHang extends javax.swing.JFrame {

    /**
     * Creates new form QLKhoHang
     */
    public QLKhoHang() {
        initComponents();
        setVisible(true);
        this.setLocationRelativeTo(null);
        JTableHeader tableHeader = tbKhoHang.getTableHeader();
        tableHeader.setBackground(new java.awt.Color(75, 139, 197));
        tableHeader.setForeground(Color.white);
        tableHeader.setFont(new Font("Tahoma", Font.PLAIN, 18));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbKhoHang = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tfSoLuong = new javax.swing.JTextField();
        tfDonVi = new javax.swing.JTextField();
        tfThang = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfNam = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfNgay = new javax.swing.JTextField();
        lbMaThanhVien = new javax.swing.JLabel();
        lbKhachHang = new javax.swing.JLabel();
        lbSDT = new javax.swing.JLabel();
        lbDiemTichLuy = new javax.swing.JLabel();
        tfDiemTichLuy = new javax.swing.JTextField();
        tfDiemTichLuy1 = new javax.swing.JTextField();
        lbDiemTichLuy1 = new javax.swing.JLabel();
        lbDiemTichLuy2 = new javax.swing.JLabel();
        tfDiemTichLuy2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton8.setBackground(new java.awt.Color(75, 139, 197));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Bán Hàng");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(0, 260, 300, 70);

        jButton9.setBackground(new java.awt.Color(75, 139, 197));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Thành Viên");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(0, 370, 300, 70);

        jButton7.setBackground(new java.awt.Color(75, 139, 197));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Nhân Viên");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(0, 480, 300, 70);

        jButton2.setBackground(new java.awt.Color(75, 139, 197));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Thống Kê");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(0, 590, 300, 70);

        jButton10.setBackground(new java.awt.Color(75, 139, 197));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Kho Hàng");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(0, 700, 300, 70);

        jButton11.setBackground(new java.awt.Color(75, 139, 197));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Đăng Xuất");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(0, 810, 300, 70);

        tbKhoHang.setBackground(new java.awt.Color(243, 232, 223));
        tbKhoHang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbKhoHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MLH", "Số lượng", "Đơn vị", "NgNhap", "NgHetHan", "XXu", "NV Phụ Trách", "Loại SP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbKhoHang.setIntercellSpacing(new java.awt.Dimension(10, 10));
        tbKhoHang.setRowHeight(35);
        tbKhoHang.setSelectionBackground(new java.awt.Color(212, 198, 187));
        tbKhoHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKhoHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbKhoHang);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(470, 260, 860, 580);

        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("NHẬP HÀNG");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(140, 30, 210, 30);
        jPanel2.add(tfSoLuong);
        tfSoLuong.setBounds(150, 90, 190, 27);
        jPanel2.add(tfDonVi);
        tfDonVi.setBounds(150, 120, 190, 27);
        jPanel2.add(tfThang);
        tfThang.setBounds(210, 150, 40, 20);

        jLabel2.setText("/");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(260, 150, 10, 15);
        jPanel2.add(tfNam);
        tfNam.setBounds(270, 150, 60, 20);

        jLabel3.setText("/");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(200, 150, 10, 15);
        jPanel2.add(tfNgay);
        tfNgay.setBounds(150, 150, 40, 20);

        lbMaThanhVien.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbMaThanhVien.setText("Số lượng: ");
        jPanel2.add(lbMaThanhVien);
        lbMaThanhVien.setBounds(30, 90, 110, 15);

        lbKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbKhachHang.setText("Đơn vị nhập: ");
        jPanel2.add(lbKhachHang);
        lbKhachHang.setBounds(30, 120, 110, 15);

        lbSDT.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbSDT.setText("Ngày Hết Hạn: ");
        jPanel2.add(lbSDT);
        lbSDT.setBounds(30, 150, 110, 15);

        lbDiemTichLuy.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbDiemTichLuy.setText("Xuất xứ: ");
        jPanel2.add(lbDiemTichLuy);
        lbDiemTichLuy.setBounds(30, 180, 110, 15);
        jPanel2.add(tfDiemTichLuy);
        tfDiemTichLuy.setBounds(150, 180, 190, 27);
        jPanel2.add(tfDiemTichLuy1);
        tfDiemTichLuy1.setBounds(150, 210, 190, 27);

        lbDiemTichLuy1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbDiemTichLuy1.setText("Mã NV: ");
        jPanel2.add(lbDiemTichLuy1);
        lbDiemTichLuy1.setBounds(30, 210, 110, 15);

        lbDiemTichLuy2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbDiemTichLuy2.setText("Loại sản phẩm: ");
        jPanel2.add(lbDiemTichLuy2);
        lbDiemTichLuy2.setBounds(30, 240, 110, 15);
        jPanel2.add(tfDiemTichLuy2);
        tfDiemTichLuy2.setBounds(150, 240, 190, 27);

        jButton1.setText("Nhập Hàng");
        jPanel2.add(jButton1);
        jButton1.setBounds(170, 320, 140, 40);

        jTabbedPane1.addTab("tab1", jPanel2);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(1420, 260, 470, 580);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cuahangtienloi/Image/Background.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1, -4, 1920, 1090);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void tbKhoHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKhoHangMouseClicked
//        DefaultTableModel tbKhach =(DefaultTableModel)jtKhach.getModel();
//        int SelectedRows = jtKhach.getSelectedRow();
//        tfMaThanhVien.setText(tbKhach.getValueAt(SelectedRows,0).toString());
    }//GEN-LAST:event_tbKhoHangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLKhoHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLKhoHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLKhoHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLKhoHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLKhoHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbDiemTichLuy;
    private javax.swing.JLabel lbDiemTichLuy1;
    private javax.swing.JLabel lbDiemTichLuy2;
    private javax.swing.JLabel lbKhachHang;
    private javax.swing.JLabel lbMaThanhVien;
    private javax.swing.JLabel lbSDT;
    private javax.swing.JTable tbKhoHang;
    private javax.swing.JTextField tfDiemTichLuy;
    private javax.swing.JTextField tfDiemTichLuy1;
    private javax.swing.JTextField tfDiemTichLuy2;
    private javax.swing.JTextField tfDonVi;
    private javax.swing.JTextField tfNam;
    private javax.swing.JTextField tfNgay;
    private javax.swing.JTextField tfSoLuong;
    private javax.swing.JTextField tfThang;
    // End of variables declaration//GEN-END:variables
}
